services:
  master:
    build: .
    container_name: mpi_master
    hostname: master
    volumes:
      - .:/app
    networks:
      mpi_network:
        aliases:
          - master

  worker1:
    build: .
    container_name: mpi_worker1
    hostname: worker1
    networks:
      mpi_network:
        aliases:
          - worker1

  worker2:
    build: .
    container_name: mpi_worker2
    hostname: worker2
    networks:
      mpi_network:
        aliases:
          - worker2

  worker3:
    build: .
    container_name: mpi_worker3
    hostname: worker3
    networks:
      mpi_network:
        aliases:
          - worker3

networks:
  mpi_network:
    driver: bridge
    