# -*- coding: utf-8 -*-
"""Avaliação_contínua_03 - Ex 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ZmjusBeG4dFBbkyXfjFjmhjJbg-27V-
"""

#Exercício 1 - Funções pré programadas

idade <- c(18,20,19,21,25,22,18,20,21,19,20,21,19,24,21)

n <- 15

#Média
mean(idade)

#Mediana
median(idade)

#Variância
var(idade)

#Desvio padrão
sd(idade)

#Coeficiente de variação
cv <- function(x) {
  sd(x) / mean(x) * 100
}

cv(idade)

#Quartis
quantile(idade, probs = c(0.25, 0.75))

#Histograma
hist(idade,
     main = "Histograma de Idades",
     xlab = "Idade",
     ylab = "Quantidads de alunos",
     border = "black",
     col = "sky blue",
     breaks = 10
)

#Box plot
boxplot(idade, main = "Box Plot", ylab = "Idades")

#Funções programadas pelo estudante

#Média
media <- function(lista) {
  soma <- sum(idade)
  comprimento <- length(idade)
  media <- soma/comprimento
  return(media)
}
media(idade)

#Mediana
mediana <- function(lista) {
  n <- length(idade)
  sorted_list <- sort(idade)
  if(n %% 2 == 0){
    ni <- n/2
    mediana <- (sorted_list[ni - 1] + sorted_list[ni]) / 2
  }
  else{
    ni <- n/2
    mediana <- sorted_list[ni]
  }
  return(mediana)
  }
mediana(idade)

#Variância Populacional
variancia_P <- function(lista) {
  n <- length(lista)
  m <- mean(lista)
  soma_de_quadrados <- sum((lista - m)^2)
  variancia_P <- soma_de_quadrados / n
  return(variancia_P)
}

variancia_P(idade)

#Variância amostral:
variancia_A <- function(lista) {
  n <- length(lista)
  m <- mean(lista)
  soma_de_quadrados <- sum((lista - m)^2)
  variancia_A <- soma_de_quadrados / (n-1)
  return(variancia_A)
}

variancia_A(idade)

#Desvio Padrão Populacional
dp <- function(lista) {
  vp <- variancia_P(lista)
  dp <- sqrt(vp)
  return(dp)
}

dp(idade)

#Desvio Padrão Amostral
dpa <- function(lista) {
  va <- variancia_A(lista)
  dpa <- sqrt(va)
  return(dpa)
}

dpa(idade)

#Coefiente De Variação Populacional:
cv <- function(lista) {
  cv <- (dp(idade)/mean(idade))*100
  return(cv)
}

cv(idade)

#Coefiente De Variação Amostral:
cva <- function(lista) {
  cva <- (dpa(idade)/mean(idade))*100
  return(cva)
}

cva(idade)

#Quartil 1:
posicao_mediana <- (n+1)/2
ordem <- sort(idade)
metade1 <- ordem[0:posicao_mediana]
q1 <- median(metade1)
q1

#Quartil 3:
posicao_mediana <- (n+1)/2
ordem <- sort(idade)
metade1 <- ordem[posicao_mediana:n]
q3 <- median(metade1)
q3